(
Dictionary[
	\Cmaj7 -> Dictionary[
		\degree -> [0, 2, 4, 6],
		\guitarDegree -> [-3, 0, 3, 7, 9, 11],
		\intervals -> [0, 4, 7, 11],
		\key -> 48,
		\root -> 0,
		\scale -> \major
	],
	\Cmaj7Sharp11 -> Dictionary[
		\degree -> [0, 2, 4, 6, 9],
		\intervals -> [0, 4, 7, 11, 18],
		\key -> 60,
		\root -> 0,
		\scale -> \major
	],
	\Csus2AddSharp11 -> Dictionary[
		\degree -> [0, 1, 3, 4, 9],
		\intervals -> [0, 2, 5, 7, 18],
		\key -> 61,
		\root -> 1,
		\scale -> \suspended
	]
]
)
